-- Esquema inicial del catalogo, para el perfil local sobre H2 en memoria.
--
-- El contenido de esta migracion no se escribio a mano: es el DDL que generaba
-- Hibernate para el dialecto de H2 a partir de ProductoJpaEntity, capturado con
-- la generacion de scripts de JPA. Copiarlo tal cual es lo que permite que
-- `ddl-auto: validate` pase, porque el tipo de cada columna es exactamente el
-- que el ORM espera encontrar.
--
-- De ahi que `categoria` sea el tipo ENUM nativo de H2 y no un varchar: es lo
-- que el dialecto de H2 elige para un @Enumerated(STRING). En PostgreSQL el
-- mismo mapeo se traduce distinto, y por eso las migraciones van separadas por
-- motor.
--
-- La restriccion de unicidad NO esta aqui a proposito: llega en V2. La base de
-- produccion ya existia con esta forma antes de que hubiera migraciones, y se
-- adopta con baseline, asi que esta version nunca se ejecuta alli. Todo lo que
-- deba aplicarse tambien en produccion tiene que ir en una version posterior.

create table productos (
    precio numeric(12,2) not null,
    id bigint generated by default as identity,
    nombre varchar(120) not null,
    descripcion varchar(500),
    categoria enum ('ALMACENAMIENTO','AUDIO','COMPUTO','CONECTIVIDAD','ENERGIA','MOBILIARIO','PANTALLAS','PERIFERICOS') not null,
    primary key (id)
);

create index idx_productos_categoria on productos (categoria);
