-- Esquema inicial del catalogo, para el perfil de nube sobre PostgreSQL.
--
-- Igual que su equivalente de H2, es el DDL que generaba Hibernate para este
-- dialecto, capturado con la generacion de scripts de JPA y no escrito a mano.
-- Reproduce exactamente la tabla que ya existe en la base de Neon, creada por
-- el ORM antes de que el proyecto tuviera migraciones.
--
-- Por eso esta version normalmente NO se ejecuta en produccion: esa base se
-- adopta con `baseline-on-migrate`, que la marca como si V1 ya se hubiera
-- aplicado. Existe para que una base vacia (otro ambiente, otra region, una
-- prueba) llegue exactamente al mismo punto de partida.
--
-- El dialecto de PostgreSQL traduce el @Enumerated(STRING) a un varchar con
-- una restriccion CHECK, mientras que el de H2 usa su tipo ENUM nativo. Es la
-- diferencia que obliga a tener una carpeta por motor.

create table productos (
    precio numeric(12,2) not null,
    id bigint generated by default as identity,
    categoria varchar(30) not null check (categoria in ('AUDIO','PERIFERICOS','PANTALLAS','COMPUTO','ALMACENAMIENTO','CONECTIVIDAD','ENERGIA','MOBILIARIO')),
    nombre varchar(120) not null,
    descripcion varchar(500),
    primary key (id)
);

create index idx_productos_categoria on productos (categoria);
